#!/bin/bash

touch ~/.bash_profile


if [[ ":$PATH:" != *":$HOME/bin:"* ]]; then 
	echo 'export PATH=$HOME/bin:$PATH' >> ~/.bash_profile
fi

mkdir -p ~/bin

curl -s -o ~/bin/screenshotr http://www.kevinbaugh.com/shell/screenshotr

chmod 755 ~/bin/screenshotr

mkdir -p ~/bin/screenshotr_bin

curl -s -o ~/bin/screenshotr/screenshotr_bin/config.cfg http://www.kevinbaugh.com/shell/screenshotr/assets/config.cfg.bk

curl -s -o ~/bin/screenshotr/screenshotr_bin/version.cfg http://www.kevinbaugh.com/shell/screenshotr/assets/version.cfg

version=$( cat ~/bin/screenshotr/screenshotr_bin/version.cfg )

chmod 755 ${config_file}>${config_file}
 
source ~/.bash_profile

clear;

echo -e "\033[32mCongratulations! You've successfully installed Screenshotr v${version}, the tool to help you manage"
echo -e "your screenshots directory."
echo
read -p "Press [Enter] to get started..."

screenshotr

exit;